name: Test

on:
  push:
  schedule:
    - cron:  "0 0 1 * *" # At 00:00 on day-of-month 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run:  bin/test
