name: Test

on:
  push:
  pull_request:
  schedule:
    - cron:  "0 0 1 * *" # At 00:00 on day-of-month 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: |
        docker run --rm --env PORT=8080 $(docker build . -q) bin/test
